/*
 * Created on 2024-09-09 ( 23:41:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.entities;

import java.io.Serializable;


/**
 * Composite primary key for entity "Song" ( stored in table "song" )
 *
 * @author Telosys
 *
 */
public class SongIdAsIdClass implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     name ;
    
    private String     album ;
    
    private String     artist ;
    
    /**
     * Constructor
     */
    public SongIdAsIdClass() {
        super();
    }

    /**
     * Constructor with values
     * @param name 
     * @param album 
     * @param artist 
     */
    public SongIdAsIdClass( String name, String album, String artist ) {
        super();
        this.name = name ;
        this.album = album ;
        this.artist = artist ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setName( String value ) {
        this.name = value;
    }
    public String getName() {
        return this.name;
    }

    public void setAlbum( String value ) {
        this.album = value;
    }
    public String getAlbum() {
        return this.album;
    }

    public void setArtist( String value ) {
        this.artist = value;
    }
    public String getArtist() {
        return this.artist;
    }


    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		SongIdAsIdClass other = (SongIdAsIdClass) obj; 
		//--- Attribute name
		if ( name == null ) { 
			if ( other.name != null ) 
				return false ; 
		} else if ( ! name.equals(other.name) ) 
			return false ; 
		//--- Attribute album
		if ( album == null ) { 
			if ( other.album != null ) 
				return false ; 
		} else if ( ! album.equals(other.album) ) 
			return false ; 
		//--- Attribute artist
		if ( artist == null ) { 
			if ( other.artist != null ) 
				return false ; 
		} else if ( ! artist.equals(other.artist) ) 
			return false ; 
		return true; 
	} 

    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute name
		result = prime * result + ((name == null) ? 0 : name.hashCode() ) ; 
		//--- Attribute album
		result = prime * result + ((album == null) ? 0 : album.hashCode() ) ; 
		//--- Attribute artist
		result = prime * result + ((artist == null) ? 0 : artist.hashCode() ) ; 
		
		return result; 
	} 

    //--- toString METHOD
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(name);
        sb.append("|");
        sb.append(album);
        sb.append("|");
        sb.append(artist);
        return sb.toString(); 
    } 

}
